name: super_container_layout
description: Widgets de conteneur stylable et de disposition modulaire en zones.
version: 0.1.0

environment:
  sdk: ^3.13.5
  flutter: ">=3.47.6"

dependencies:
  flex_color_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.4
  material_ui: ^1.5.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
